---
output:
  pdf_document: default
  word_document: default
  html_document: default
fontsize: 12pt
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage[left]{lineno}
geometry: margin=1in
csl: ecology.csl
bibliography: FF_refs.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

Running Head: Reburns Reduce Sagebrush Diversity.

Title: Repeated Fires Reduce Plant Diversity in Low-Elevation Wyoming Big Sagebrush Ecosystems (1984-2014).

\vspace{5mm}


Authors:\newline
\newline
Adam L. Mahood *\newline
Department of Geography\newline
University of Colorado Boulder\newline
GUGG 110, 260 UCB\newline
Boulder, CO 80309-0260\newline
\newline
Jennifer K. Balch\newline
Department of Geography\newline
University of Colorado Boulder\newline
GUGG 110, 260 UCB \newline
Boulder, CO 80309-0260\newline
\newline
*Corresponding author\newline

\newpage
\linenumbers

**Abstract**

Sagebrush in the Great Basin is one of the most imperiled ecosystems in North America, having lost about half of its original 62 million hectare extent. Annual grass invasions are known to be increasing wildfire occurrence and burned area, but the lasting effects (> five years post-fire) that the resulting reburns have on these plant communities are unclear. We created a fire history atlas from 31 years (1984 to 2014) of Landsat-derived fire data to sample along a fire frequency gradient (zero to three fires) in an area of northern Nevada that has experienced frequent fire in this time period. 32% of our study area (13,000 km$^2$) burned in large fires (over 404 ha) at least once, 7% burned twice, and 2% burned three or more times. We collected plant abundance data at 28 plots (N=7 per fire frequency), with an average time-since-fire of 17 years. We examined fire’s effect on plant diversity using species accumulation curves, alpha-diversity (Shannon's dominance, Pielou's evenness and number of species), and beta diversity (Whittaker, Simpson, and Z indexes). For composition, we used non-metric multidimensional scaling. We then used PERMANOVA models to examine how disturbance history, temperature, precipitation and aridity around the time of the fire affected subsequent community composition and diversity.

One fire fundamentally changed community composition and reduced species richness, and each subsequent fire reduced richness further. Alpha diversity (dominance and number of species) decreased after one fire. Beta diversity declined after the third fire. Cover of exotics was 10% higher in all burned plots, and native cover was 20% lower than in unburned plots, regardless of frequency. PERMANOVA models showed fire frequency and antecedent precipitation as the strongest predictors of beta diversity, while time since fire and vapor pressure deficit for the year of the fire were the strongest predictors of community composition. Given that a single fire has such a marked effect on species richness, and repeated fires reduce richness and beta diversity, we suggest that in lower elevation big sagebrush systems fire should be minimized as much as possible, perhaps even prescribed fire. Restoration efforts should be focused on timing with wet years on cooler, wetter sites.


*Key Words: Bromus tectorum, cheatgrass, fire, sagebrush, fire frequency, repeated fire, biodiversity, community composition, Artemisia tridentata ssp. wyomingensis*

**1. Introduction**

<!-- The main problem -- get into wyoming BS and elevation -->

Wildfire activity has been increasing across the western U.S. since the 1980s [@Dennison2014; @Westerling2016; @Westerling2006; @Balch2017], and this is leading to concern among land managers in the U.S. Great Basin [@Miller2013; @IRMT2016; @Chambers2017]. This trend will likely continue as rising temperatures and more frequent drought events increase the probability of fire [@Krawchuk2009a; @Moritz2012a; @Liu2013], and as these climatic factors combine with increased human ignition pressure [@Balch2017] and land use change [@Bowman2011] to increase the length of the fire season [@Wotton1993; @Jolly2015]. This increased fire activity is one contributing factor to the loss of approximately half of the area of sagebrush (*Artemisia tridentata*) shrubland communities, which once occupied over 600,000 km$^2$ in the western US. Much of this land  is now dominated by cheatgrass (*Bromus tectorum*) [@Bradley2008], an introduced annual grass [@Davies2011]. This in turn is initiating a positive feedback, wherein invading plants increase the probability of fire, and increased fire activity stimulates more annual grass invasion [@DAntonio1992; @Brooks2004b; @Balch2013]. The result is a fire return interval that has decreased from a historical range of 100-342 years for intact sagebrush [@Baker2006; @Bukowski2013] to 78 years in invaded areas [@Balch2013], to as low as 3-5 years in cheatgrass-dominated areas in the Snake River Plain [@Whisenant1990]. This increase in fire activity results in more areas that are burned multiple times, and the lasting effect this has on plant communities’ biodiversity and composition is relatively unknown. There are relatively few studies on the impacts of fire after more than 5 years [but see @Beck2009; @Reed-dustin2016], and fewer still that analyze the impacts of repeated fires in the same location [@Miller2013].

<!-- mgmt: sage grouse -->

There are at least 40 vertebrate species of conservation concern associated with sagebrush habitats [@Rowland2006], including the greater sage grouse (*Centrocercus urophasianus*). Greater sage grouse depends on sagebrush for its habitat and has been a management priority by land managers [@Chambers2017]. Optimal shrub cover for sage grouse is 15-25% with over 15% bunchgrasses and forbs [@Beck2009]. Fire is one of the top 2 threats to the greater sage grouse in the western part of its range [@Brooks2015], and the loss of sagebrush due to wildfire has contributed strongly to its population declines over the past 30 years [@Coates2016]. Land management agencies have linked fire management with long-term conservation goals focused on sagebrush ecosystems and the greater sage grouse [@Chambers2017].

There is emerging consensus among researchers and land managers that lower elevation Wyoming big sagebrush (*A. tridentata* ssp. *wyomingensis*) ecosystems are not resilient to fire [@Chambers2014] and should be prevented from burning whenever possible, while higher elevation Mountain big sagebrush (*A. tridentata* ssp. *vaseyana*) ecosystems may still recover naturally [@Hanna2015] or with restoration by seeding [@Knutson2014]. Several authors have recommended attempting to reduce the size and frequency of wildfire, and stopping the use of prescribed fire [@Whisenant1990; @Lesica2007; @Baker2006; @Beck2009], while also reducing grazing [@Shinneman2009; @Ellsworth2013]. Others have urged caution with the use of prescribed fire [@Shinneman2016; @Reed-dustin2016; @Davies2009]. There has been disagreement in the past about the historical fire return interval for Wyoming big sagebrush. It has been characterized as being every 35 -- 100 years [@Schmidt2002], every 100 -- 240 years [@Baker2006], to every 171 -- 342 years [@Bukowski2013]. This discrepancy has important management implications, leading to disagreement as to which stressors or disturbances (e.g. grazing, fire) need to be increased or decreased in order to manage for healthy sagebrush ecosystems. The lower estimations imply the system is fire-dependent and requires frequent burning in order to persist, while the upper estimates suggest fire-sensitivity.

<!-- biodiverstiy -->
Wyoming big sagebrush assemblages are generally agreed to be an endangered ecosystem and fire and the invasive plants that generally colonize afterwards are thought to be two major drivers of declining biodiversity in this system [@Davies2011a]. Cover of introduced annual grass species have been mostly observed to be negatively related to species richness and native diversity [@Bansal2016; @Davies2011; @Gasch2013], but over a 45 year period @Anderson2001 found that while introduced annual grass cover was negatively correlated with cover of native species, species richness was unrelated. While fire is strongly correlated with annual grass cover in this system at regional scales [@Balch2013], it has also been shown to be an unimportant predictor variable for both exotic cover and species richness in eastern Washington [@Mitchell2016].

<!-- Long term effects - composition-->
Post-fire communities of introduced annual grasses are affected by both fire frequency and time since fire. Cheatgrass cover can increase initially after fire, then stabilize above its pre-fire cover after 2-5 years [@Reed-dustin2016], but positive linear relationships between time since fire and cheatgrass cover have also been observed [@Shinneman2009], as well as areas where cheatgrass declined and was replaced by perennial grasses [@West2002; @Hanna2015]. Pre-fire community composition might explain the inconsistency in results. Cheatgrass can come to dominate areas with fire-intolerant natives post-fire, but in areas with pre-fire populations of fire-tolerant species (e.g. *Poa secunda*) these species can regenerate following fire [@Davies2012; but see @Bagchi2013].

Precipitation, temperature and aridity affect both fire occurrence and the subsequent recovery of plant communities. Unlike most forested systems in the western US, burned area in Great Basin sagebrush systems is best predicted by antecedent precipitation [@Abatzoglou2013; @Pilliod2017]. Precipitation also drives the invasion of cheatgrass into lower elevation sagebrush systems [@Chambers2007], which increases the probability of fire for several years due to the persistence of the litter it leaves behind [@Pilliod2017]. Cheatgrass invasion increases the continuity of fuels [@Davies2013] and burned area [@Balch2013], thereby reducing the number of unburned patches that provide the native seed sources critical for recolonizing burned areas. Unburned patches are essential for sagebrush regeneration as almost every species in this genus is a seed obligate and the seeds generally fall no more than 30 meters from the mother plant [@Meyer1994]. Once established, a sagebrush seedling needs to be able to withstand drought conditions in the summer to survive and be recruited into the population [@Meyer1994].

<!-- what we did  -->
Here, we explored how sagebrush community composition and diversity responded to increasing fire disturbance by constructing a fire history atlas and sampling plant communities that burned zero to three times between 1984 and 2014 in the Central Basin and Range ecoregion. We constrained soil, ecological site type, elevation and climate and sampled blocks of plots stratified along a gradient of 0-3 fires. Our first hypothesis was that community composition would change drastically between unburned and burned plots, but remain similar between burned plots of different fire frequencies. This was our expectation because in the Great Basin there are vast areas of sagebrush which are generally unburned in the last 30+ years, and burned areas are almost always completely dominated by cheatgrass, along with a handful of exotic forb species and a native grass, *Poa secunda*. These cheatgrass-dominated areas all appear very similar, regardless of fire frequency (Figure 1). But we suspected that there would be a signal on plant diversity after multiple fires, due to selective pressure against fire-intolerant plants. Thus our second hypothesis was that alpha diversity (Shannon-Weaver index, Pielou Evenness, and the number of species in a sampling unit), beta diversity (continuity or turnover of species between plots) and the extrapolated species richness (with plots pooled by fire frequency), would decrease with increasing fire frequency. Our third hypothesis was that cheatgrass abundance would have a negative relationship with plant diversity. Our fourth hypothesis was that temperature, vapor pressure deficit and precipitation around the time of the fire would exert a lasting influence over post-fire community composition and diversity. This is based on evidence that the effects of introducing species at the beginning of secondary succession can be long-lasting [@Veen2018], and in this system the assemblage of species that are able to successfully colonize an area after a fire depends on their abilities to compete for moisture and tolerate drought [@Meyer1994].

**2. Methods**

**2.1. Study Area**

We conducted the study in a 13,000 square kilometer region in northern Nevada (Figure 2). The region has hot, dry summers and cold, wet winters. Annual precipitation averages 293 mm, falling mostly from November to May. Mean temperatures range from 21.8 degrees Celsius in July to -1.4 degrees Celsius in December [@PRISM2016]. The region consists of mountain ranges that run north-south, and the sagebrush ecosystems generally lie on the lower slopes of the mountains; our sites ranged from 1272 to 1696 meters in elevation (median 1458, SD 99). From 1984 to 2014, 32% (4096 square kilometers) of the study area burned in large fires (over 500 acres) at least once, 7% burned twice, and 2% burned three or more times (Table S1).

**2.2. Site Selection**

We used a block sampling design, with each block containing one site from each of four fire frequencies (zero to three), and all fires occurring at least five years before the study. We used geospatial data representing ecosystem state factors [*sensu* @Amundson1997] to design a sampling scheme that constrained all other factors. We used the LANDFIRE [@Rollins2009] biophysical setting layer to eliminate all vegetation types except big sagebrush shrubland. The LANDFIRE data has 62-68% classification accuracy for shrublands [@Zhu2006]. We used soil data from the Natural Resource Conservation Service to include only areas in the Loamy 8-10 precipitation zone [@wss2016]. We chose this particular zone simply because it was the most common type in our study area within the big sagebrush shrubland biophysical setting. We used the Land Treatment Digital Library to exclude areas that had undergone intensive restoration activities [@ltdl2013]. Excluding private and military land, and areas more than five miles from a road eliminated impractical plot locations and held human influence somewhat constant.

We accounted for additional, unknown disturbances such as grazing by using a block sampling design, and stratifying our statistical analyses by these blocks. Long-term grazing data were not available. Therefore, we assumed that plots within blocks were close enough together that they had experienced similar grazing pressure. Additionally, we visually assessed the impact of grazing on-site, aggregated what records we could for the allotments in our study (billed animal unit months (AUM) provided by the Bureau of Land Management), and normalized AUM by unit area and included these data in our statistical modeling. 

Once we constrained the area to a consistent sampling space, we used Landsat-derived fire data to stratify the space along a fire frequency gradient. To generate fire history maps, we first extracted only the values two to four (low, medium and high severity) from each yearly burn severity mosaic from the Monitoring Trends in Burn Severity project [MTBS; @Eidenshink2007], as these were the values where one can be reasonably certain that they actually burned. Unburned patches and post-fire green-up, which could be caused by a response to fire or an unburned patch, were excluded. To generate fire frequency maps, we reclassified each yearly layer to a binary grid, and summed all 31 layers. To avoid areas with less certain fire frequencies, we then converted the MTBS fire perimeter polygons to layers of fire frequency to extract only the grid cells where the frequency from the polygons matched the frequency from the reclassified raster grid. To generate last-year-burned maps, we reclassified each severity mosaic (values two to four) to the fire year, and calculated the maximum year for the entire time period for each pixel. To eliminate areas that had burned more recently than 2014, we masked pixels that burned in 2015 according to the MODIS MCD64 burned area product [@Giglio2009].

@Kolden2015 have brought up several shortcomings for the use of the MTBS burn severity mosaics, in particular inconsistent development of class thresholds and a lack of empirical relationships between the classified values and ecological metrics. Because we only used these data to get a more precise estimate of fire occurrence, (i.e. we used it to eliminate areas of uncertainty) rather than using the severity data as an independent variable for analysis, we thought it sufficient to use these data in this state. Another shortcoming that should be noted is that there is no practical way for us to know what these sites looked like before the earliest fires in the fire record. The fact that our unburned control plots were all mature sagebrush is one piece of evidence suggesting these sites were mature sagebrush pre-fire, but we cannot be 100% certain, and this is a shortcoming of all chronosequence studies [@Walker2010].

We selected seven blocks in our sampling space in accessible areas where there was a range of fire frequencies and unburned areas for controls within close proximity (0.5 - 10 km). Within each block, we created spatially balanced random points [@Theobald2007] for each fire frequency, and sampled one plot for each fire history class within the block. At each block, we first sampled the unburned control plot to confirm that the area was indeed the correct vegetation type, and then sampled burned plots. After navigating to the predetermined coordinates for each plot we first confirmed the physical characteristics (soil type, lack of obvious restoration, lack of obvious overgrazing) were within the constraints of our sampling design. If a predetermined point was not suitable (e.g. soil was too rocky or sandy, an unburned control plot had obviously burned, or it was the wrong ecological site type), we referred to georeferenced PDFs of our fire history atlas that we accessed with a simple application (Avenza Maps https://www.avenzamaps.com/) on a mobile device and located nearby areas within the site that were suitable. When a suitable area was found we used a random number generator to pick a random bearing and a random distance, and navigated to the new plot location.

We sampled 28 plots that fell along a gradient of fire frequency (zero to three fires; N = seven plots per frequency) and a range of times since fire (4-31 years; mean = 17.6, std = 6.6; Figure 2). Because most of the fire effects research in this system has been done within five years of a fire, we aimed to have the time since fire of all of the plots greater than or equal to 5 years. We encountered 53 plant species - 12 were introduced and 41 were native (Table S2). 


**2.3. Field Sampling**

**2.3.1. Plot Establishment**

We used GPS to navigate to predetermined plot locations. Upon arrival we established a permanent marker at the southwest corner of the plot. We recorded the slope, aspect, distance to the nearest *A. tridentata* individual or other shrub species, the topographic curvature of the site (convex, concave, flat), evidence of ecological restoration, grazing signs, and evidence of past fires. We then delineated a 50 x 50 meter plot, and placed pin flags at 9 randomly determined 1m^2^ subplots within the plot with a minimum spacing of 3 meters. @Pilliod2013 found this sampling density sufficient for this ecosystem, if supplemental methods are used to estimate disparate functional groups like trees and shrubs. Hence, we used the point-quarter method as a supplement to estimate shrub cover (see Pilliod & Arkle [-@Pilliod2013] for detailed methods). 

**2.3.2. Vegetation**

To explore how fire frequency influences community composition and diversity, we measured the occurrence and abundance of all species. We identified and recorded occupancy data for every species within each subplot, and took a photograph from nadir with an Olympus Stylus TG-870 digital camera to be analyzed later for percent cover. 

We used 'Samplepoint' software [@Booth2006] to analyze the digital photographs for percent cover. We prepared photographs for analysis by cropping them to the 1 m x 1 m area of the subplot. Then we used Samplepoint to overlay a regular grid of 100 points on each picture, and at each point identified whether it was litter, bare ground, rock, dung, or a plant. If it was a plant, we identified it to species with the aid of the occupancy data recorded at the plot. These data were then converted to percent cover. If we recorded a species as present within the subplot, but it was missed by the photographic analysis, we recorded it as 0.5% cover. 

**2.3.3. Environmental Data**

Aspect was converted to folded aspect [folded aspect = |180 - |aspect - 225||; @McCune2002]. This results in an approximation of heat load ranging from zero (northeast) to 180 (southwest). Elevation was extracted from 10m resolution digital elevation models. The study sites were situated among six grazing allotments. To learn how climate before, during and after the fire event affected the subsequent community composition and diversity, we extracted monthly maximum vapor pressure deficit, maximum temperature, and precipitation for the years before during and after the most recent fire at each plot. Maximum temperature and maximum vapor pressure deficit were averaged for the entire year before during and after, and precipitation was averaged for the two winters (November - May) prior and one after. We used monthly data provided by the PRISM climate group [@PRISM2016] for all climate variables. Variables used in modeling are provided in Table 1. We also sampled soil C and N (see Mahood [-@Mahood2017] for detailed methods). 

**2.4. Statistical Analysis**

**2.4.1. Community Composition and Environmental Variables**

To analyze how fire frequency affects community composition, we used non-metric multidimensional scaling (NMDS). We ran a rank correlation test for fire history gradients against a matrix of relative cover of species per plot to determine the best hierarchical clustering method for creating a dissimilarity matrix. We used this index for NMDS to examine how those fire history characteristics affected the floristic composition. To assess which species and environmental variables had the most influence on community composition, we added those variables to the ordinations using the 'envfit' function from Vegan, with 9,999 permutations and stratified by the study block. Then we grouped species by their biogeographical origin (i.e. native or exotic), and used Tukey's test to assess how fire frequency influenced native cover, exotic plant cover and cheatgrass abundance.

**2.4.2. Species Richness, Alpha Diversity and Beta Diversity**

We created species accumulation curves grouped by fire frequency to assess how fire frequency affected species richness. This is different from alpha diversity in that the species accumulation curve is estimating number of species across all of the sites within each group with each added plot, as opposed to simply calculating a diversity index for each plot. We used the sample-based rarefaction method [@Chiarucci2008; @Vegan2016; @R]. We used Tukey's Honest Significant Differences test (hereafter, Tukey's test) to see if different fire frequencies influenced alpha diversity (Shannon-weaver, Pielou evenness, and number of species per plot). There are several ways to quantify beta diversity, most of which are grouped into "measures of continuity" and "measures of gain and loss" [@Koleff2003]. We used the "Z" index and Whittaker's original beta diversity index for continuity measures, and Simpson's index (based on G. Gaylord Simpson's asymmetric index [@Simpson1943] and modified by @Lennon2001, not to be confused with Edward H. Simpson's Index [-@Simpson1949]) for a measure of gain and loss. To see how beta diversity differed between fire frequencies, we modeled the homogeneity of dispersion of those matrices [@Anderson2006], and ran pairwise permutation tests [@Legendre2011] on these models with 9,999 permutations, stratified by the study blocks. To assess the influence of cheatgrass abundance on alpha and beta diversity, we used linear mixed models [@Pinheiro2017] with the study block as a random effect. We included elevation as a fixed effect in addition to cheatgrass due to its strong correlation with temperature and moisture availability, and ecosystem resistance and resilience [@Chambers2014]. We ensured that predictors had no multicollinearity using a variable inflation factor test [@Fox2011], and used the partial coefficient of determination [@Jaeger2017] to determine the cheatgrass component of the model. To aid visualization, we removed the partial effects of elevation from the dependent variables [@Hohenstein2018].


**2.4.3. Modeling Which Fire and Climate Variables Drive Post-fire Composition and Diversity**

To assess how pre- and post-fire climate, along with soil and other environmental variables (Table 1) affected post-fire community composition and diversity, we used permutational multivariate analysis of variance (PERMANOVA). PERMANOVA uses a dissimilarity matrix as the response variable, and columns from a separate data frame as the predictors. It makes the assumption that groups being modeled have homogeneous dispersions. If the test is run on groups with heterogeneous dispersions, it is vulnerable to type 1 error [@Anderson2013]. To account for this we built multivariate homogeneity of groups dispersions (MHGD) models on our community clustering and beta diversity matrices grouped by block, fire frequency, and burned vs unburned. We then ran ANOVAs and Tukey's test on each model, with p values below 0.05 considered to be an indication of heterogeneous dispersions. After removing variables with multi-collinearity, we built PERMANOVA models with both community clustering and beta diversity matrices using an additive model-building process, with 9,999 permutations and stratifying the permutations by the study blocks, with the aim of producing parsimonious models.

**3. Results**

**3.1 Community Composition Fundamentally Changed After One Fire**

The rank index test showed the Kulczynski index to have the most consistent high scores across gradients of fire history characteristics, so we used this index for our hierarchical clustering and NDMS analyses. NMDS (Non-metric fit, R$^2$ = 0.992, Linear fit, R$^2$ = 0.972) showed 7 unburned plots clustered around high abundances of *A. tridentata*, and 18 burned plots clustered around *B. tectorum* (Figure 3). Two thrice-burned plots were dominated by exotic annual forbs (*Sisymbrium altissimum* and *Erodium cicutarium*) and one was dominated by the native perennial grass *P. secunda* (these are the three thrice-burned plots outside of the "burned" ellipse). The ordination showed a clear separation between burned and unburned plots, but fire frequency was not significantly correlated with the ordination, nor were any environmental variables.

For the Tukey's tests of exotic versus native cover, there were differences between unburned and burned plots (p < 0.05) for both exotic (increased by 10%) and native cover (decreased by 20%), and no differences among the burned plots. (Figure 4a-b). After dividing the mean cover estimates into native and exotic life form groups (annual and perennial graminoids and forbs, and shrubs), we saw lower native shrub cover for burned plots fire (24% to 3%), coupled with higher annual grass cover (4% to 14%; Figure 5).

**3.2 Plant Biodiversity Decreased with Each Successive Fire**

We found a decline in plant diversity at sites that had burned more frequently. Species richness estimates declined as fire frequency increased (Figure 6, Table S3). The number of species and the Shannon-weaver index were higher in unburned plots, but the differences were not significant, and Pielou evenness was not different between frequencies (Figure 4c-e). All three indexes of Beta diversity followed very similar patterns, so we only report on Whittaker's index here. It was not different between zero and two fires, and lower for thrice-burned plots (Figure 4f), meaning that there is less dissimilarity within the group of thrice-burned plots, and more dissimilarity within the other groupings.

**3.3 Alpha Diversity and Evenness Decreased with Cheatgrass Abundance**

Cheatgrass abundance had a negative relationship with Shannon-weaver diversity (p << 0.05, partial R$^2$ = 0.65) and Pielou evenness (p << 0.05, partial R$^2$ = 0.51), a weak negative relationship with the number of species (p < 0.05, partial R$^2$ = 0.24), and no relationship to beta diversity (p > 0.5, partial R$^2$ = 0.08; Figure 7, Table 2). Elevation was important in all models except Pielou evenness (Table 2).


**3.4 Different Climate and Fire Variables Predict Post-Fire Compsition and Diversity**

PERMANOVA models showed that fire history and environmental factors influenced community composition and beta diversity differently. ANOVAs and Tukey's tests on MHGD models showed no heterogeneity in groups dispersions for both beta diversity and hierarchical clustering (p > 0.05 for all models). Community composition after fire was most affected by fire frequency, time since fire, maximum vapor pressure deficit of the year of the fire, and the interaction between fire frequency and time since fire (Table 3, R^2^ = 0.55). The relatively low amounts of variation accounted for by the individual variables indicates these are subtle effects. Beta diversity on the other hand was influenced most by winter precipitation one and two years prior to the fire, fire frequency, and the interaction between winter precipitation one year prior and max temperature for the year after the fire (Table 4, R^2^ = 0.62). Here, the effect was more pronounced, as more variation accounted for by the three most statistically significant variables (fire frequency and precipitation one and two winters prior to the fire).  

**4. Discussion**

The purpose of this study is to assess how Wyoming big sagebrush plant communities respond to being burned repeatedly before returning to their prior condition. The combination of a 32-year fire history atlas and the use of the RRQRR [@Theobald2007] to randomly stratify the sampling blocks over a large area provides broad-scale statistical inference for the lower elevation (<1500 m) portion of the Wyoming big sagebrush ecosystem. These lower elevation sites generally experience higher temperatures and lower soil moisture, and it is well documented that they have lower resilience after wildfires [@Chambers2014]. We did not detect recovery of Wyoming big sagebrush at our sites, and also found that while the cover of Bromus tectorum does not change with successive fires, the number of species in the species pool does decrease, and that biodiversity decreases with cover of *B. tectorum*. The results of this study may seem to conflict with other recent studies documenting Wyoming big sagebrush sagebrush recovery in the Great Basin [e.g. @Shinneman2016; @Ellsworth2016]. But all of the studies we are aware of showing sagebrush recovery were conducted at cooler, wetter sites, where it is well documented that Wyoming big sagebrush is more resilient to fire [@Chambers2014].

Coupling the 30+ year fire history atlas created here with intensive field sampling offers a unique opportunity to explore plant diversity and composition changes in areas that have relatively high fire frequencies, such as grass-dominated or grass-invaded areas [@Balch2013]. As annual grass invasions and their alterations to fire regimes are a global phenomenon [@DAntonio1992; @Brooks2004b], this type of study design will be useful for understanding the consequences of changing fire regimes in other regions. Additionally, new algorithms are being developed that will lead to more accurate and precise fire data products [e.g. @Hawbaker2015a], leading to more nuanced fire history atlases, and thus more precise sampling stratifications -- especially now that burn severity information can be easily incorporated [@Eidenshink2007]. 

**4.1. Community Composition Fundamentally Changes After One Fire**

In lower elevation *A. tridendata* ssp. *wyomingensis* systems, our results show that one fire can convert this shrub-dominated system to one composed mainly of introduced annual grasses and forbs, and we demonstrate that this new state can persist for decades with little sign of recovery to its prior condition. While almost all of our burned plots were dominated by cheatgrass, several thrice-burned plots were dominated by *P. secunda* or exotic annual forbs (see figure 3, where there are 3 plots that are outside the confidence envelope containing all other burned plots). This corroborates previous work showing that fire can push cheatgrass-invaded grassland and shrubland communities into those dominated by cheatgrass,  *P. secunda*, and exotic forbs, while uninvaded sites, or sites that are invaded but still have significant bunchgrass communities, can persist in a state of native bunchgrasses and forbs [@Davies2012; @Reisner2013; @Condon2018]. Other studies have found that topography can be a mediating factor, with native bunchgrasses more likely to persist on steeper, more north-facing slopes in the face of invasion and disturbance [@Rodhouse2014; @Reed-dustin2016]. One hypothesis that we were not able to test in this study is that increasing fire frequency may select for more fire-resilient plant functional traits. More research is needed to investigate the relationship between fire frequency and functional traits. While it has been demonstrated that *B. tectorum* establishes immediately post-fire and can persist in the shorter term [@Davies2012; @Hanna2015], we show that this novel grass state can persist for long periods (i.e. > 17 years), corroborating recent work [@Reed-dustin2016]. If there was recovery our study design would have enabled us to detect it, as Wyoming big sagebrush has been found to recover from disturbance in as little as nine [@Wambolt2001] to 20 years [@Shinneman2016] following fire, and our fire history atlas goes back 32 years. 

**4.2. Biodiversity Decreases with Each Subsequent Fire** 

Here we show that over a three decade period repeated fires had long-lasting effects on community composition and biodiversity in Wyoming big sagebrush ecosystems. Species richness declined with increasing fire frequency, but measures of alpha and beta diversity decreased after one and three fires, respectively (Figure 4a-b). Species accumulation curves demonstrated that repeated fires are decreasing the overall pool of species from which an individual patch might draw from. So while there may not have been significant differences in alpha diversity as fire frequency increased, as the number of species each plot can draw from decreased, this signal manifested itself when beta diversity declined after three fires.

We found negative relationships between cheatgrass abundance and alpha and beta diversity, as we hypothesized, but no relationship between cheatgrass abundance and the number of fires. Establishment and dominance of cheatgrass after fire is well documented [@Balch2013; @Whisenant1990], and the relationship between fire and species richness is clear from this work. This implies that once an area is invaded by cheatgrass, the competitive effects from its increased abundance combine with its effect on fire frequency to exclude species that either cannot compete for moisture or cannot survive fire. It should be noted that because we selected sites that had burned at least three times since 1984, we may have biased our results to be applicable to only those areas that are susceptible to initiating a grass-fire cycle. 

**4.3. Time Since Fire and Vapor Pressure Deficit Drive Community Composition**

PERMANOVA models showed that fire history and climate variables affect diversity and community composition differently. Composition was found to be influenced by both fire frequency and time since fire, and high vapor pressure deficit the year of the fire. This suggests that drought stress exerts a significant influence on the particular plant species that will survive and persist after a fire, and this effect can still be detected decades after the fire burned. @Shinneman2016 also found that climatic variables around the time of the fire influence the eventual composition, namely winter precipitation the year after the fire was beneficial for sagebrush recovery, but winter precipitation 2 years later had a negative effect. Elevation and recovery have been shown to be positively related in this system [@Knutson2014], and most of the studies showing fast recovery times were done at higher elevations and latitudes [@Wambolt2001; @Ellsworth2016; @Hanna2015], in areas with long-term grazing exclusion [@Ellsworth2016], or on sites that were specifically selected because their topographic position was such that there was potential for sagebrush recovery [@Shinneman2016]. Here, we found that on low elevation sites, even after an average of 17 years, post-fire sagebrush cover was very low [<6%; also see @Reed-dustin2016]. These differences in recovery rates (i.e. 9-20 years at cooler sites vs no detectable recovery at hotter sites) could be due to a slowing down of recovery rates as the system loses resilience with increasing drought stress at hotter sites, while cooler sites have not yet experienced sufficient drought stress to hamper recovery [*sensu* @VandeLeemput2017].

<!-- also add in rodhouse 2016 - mediating effect of topography in there-->

**4.4. Fire Frequency and Antecedent Precipitation Drive Beta Diversity**

Beta diversity was most heavily influenced by fire frequency, precipitation for the two wet seasons prior to the fire, and an interaction between antecedent precipitation and maximum temperature for the year after the fire. Antecedent precipitation has been shown in other studies to be an important predictor of fire occurrence and burned area in this system [@Abatzoglou2013; @Balch2013]. Since this is a fuel-limited system, high precipitation increases fine fuel loads and continuity [@Davies2013], leading to higher fire probability, more homogeneously burning fires, and larger extents. Increased fine fuel loads could also be the driving factor behind decreasing diversity. Following highly contiguous and extensive fires there would be fewer unburned patches as seed sources which are essential for the seed-obligate sagebrush to reestablish quickly [@Shinneman2016]. In addition, Wyoming big sagebrush is an opportunist in reproduction, setting most of its seed in wet years [@Meyer1994] during the short window in early spring when enough water is available in the soil for plants to uptake nutrients [@Ryel2010; @Schlaepfer2014]. So, in the years that Wyoming big sagebrush is maximizing its expenditure on reproductive resources, increased horizontal fuel continuity of invasive annual grasses [@Davies2013] a) increases the probability of burning, and b) increases interspecific competition for resources post-fire. This may result in a more homogeneous post-fire landscape populated mostly by fire-tolerant plants. 

**4.5. Management Implications**

This work adds to the existing body of literature that suggests that in low elevation (< 1700m) Wyoming big sagebrush systems wildfire should be minimized due to the negative effects of single and repeated fires on community composition and biodiversity. The reality is that wildfire can not be prevented, but fire suppression policies and practices could be crafted to maximize the number and size of unburned patches within burns to increase the probability that Wyoming big sagebrush and other native seed-obligates recover post-fire. These results also imply that prescribed burning is a risky proposition with potentially disastrous consequences for biodiversity and ecosystem structure and function. However, we did not directly assess the influence of prescribed fires in this study. Prescribed fires typically are conducted at a cooler time of year outside of or at the shoulder of the fire season, and may have different ecological effects due to the phenological stage plants would be in at this different time of year, as well as the lower burn severity that would be expected due to cooler ambient air temperatures and higher soil moisture. At a cooler, wetter site where grazing has been excluded since 1994, @Ellsworth2016 detected the recovery of sagebrush 17 years after prescribed fires were conducted in late September 1997, which is the natural end of the fire season at that location. Two other studies at higher latitudes concluded that prescribed burning to be an unwise action even at those wetter sites. @Beck2009 studied an area in southeast Idaho that was burned in late August 1989 by prescribed fire 14 years post-fire for its utility in improving sage grouse habitat. They recommended against prescribed fires due to the lack of recovery of sagebrush. @Wambolt2001 found minimal benefit to the herbaceous plant community at 13 sites that had burned in prescribed fires in Western Montana, with little shrub recovery 6-15 years after fire. Thus, there is conflicting evidence on the use of prescribed fires for management objectives even at cooler wetter sites, providing less optimism for the use of prescribed fires in the lower elevation portion of the Wyoming big sagebrush ecosystems studied here. Future research could focus on comparing low elevation Wyoming big sagebrush sites that have been burned in prescribed fires in the past paired with nearby areas that burned in wildfires, with particular emphasis on teasing out the effects of seasonality and burn severity.

Our results from PERMANOVA modeling suggest that the success of post-fire restoration efforts will depend not only on elevation and topographic conditions [@Arkle2014], but also the climatic conditions that occur around the time of the fire. This could mean that in a very dry year less money is spent on restoration efforts on low elevation sites, focusing instead on higher elevation sites and cooler aspects, and in wet years directing more funding towards those more vulnerable low elevation, southwest-facing sites. 

Disagreement on the actual historical fire rotation limits our ability to determine if Wyoming big sagebrush is fire-sensitive or fire-resistant. However, this question may be irrelevant given the disruption and interaction between invasive annual grasses and fires. We demonstrate that when both fire and invasive annual grasses operate in conjunction, sagebrush is fire-sensitive. Moreover, we show that an alternate exotic grass state can persist for 17 years post-fire even with only a single burn. This makes the use of prescribed burning problematic, as the risk of a fire-prone grassland establishing after a fire likely outweighs the potential benefits of a prescribed fire. Our results are specific to lower elevation (< 1700m), dryer, hotter Wyoming big sagebrush sites, and it remains to be explored how sagebrush at higher elevations and latitudes responds to increasing fire frequency, and how it will respond under future climate change scenarios. However, if temperatures continue to rise as projected in this region [@Garfin2014], those areas may also become susceptible to a strong grass-fire cycle. Overall, this effort demonstrates that sagebrush communities are vulnerable to repeated fires [@Seipel2018], which should be taken into account in land management decisions [@Chambers2017] that attempt to conserve or restore these valuable ecosystems, and the threatened species that they harbor.

**5. Acknowledgements**

We are grateful for the assistance of Nick Whittemore and Kathleen Weimer for their assistance in the field and in the lab. We thank Tom Veblen and Carson Farmer for comments on previous versions of the manuscript. We appreciated the constructive criticism from three anonymous reviewers which greatly improved the paper. Thanks to Max Joseph for help with the data analysis. We are also very grateful for the support of the Nevada Bureau of Land Management, and the Central Nevada Interagency Dispatch Center. This work was funded by the National Aeronautics and Space Administration Terrestrial Ecology Program under Award NNX14AJ14G, and start-up funding from the Department of Geography at CU Boulder.

**6. Literature Cited**
\singlespacing
